spring:
  application:
    name: service-auth
  ##解决jvm使用的冲突，tomcat中不同的server 注册jmx必须使用不同的jvm
  jmx:
    default-domain: service-auth
  profiles:
    active: test
## mybatis 配置
ibatis:
  typeAliasesPackage: com.service.auth.entity
  mapper:
    locations:
      test: classpath:mapper/test/*.xml
##服务监听的端口号
server:
  port: 9098

