spring:
  # redis configuration
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        max-wait: -1ms
        min-idle: 2
      shutdown-timeout: 200
    password: hejian.1
    port: 6379
    timeout: 5000
    database: 0

##fsAppByCatering库的数据源配置 测试环境
datasource:
  name: fsAppByCatering
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jdbc-url: jdbc:sqlserver://localhost:8899;DatabaseName=fsAppByCatering
  username: username
  password: password

##发现服务的默认域
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
## swagger config
server:
  gateway:
    ip: localhost
    port: 8888
swagger:
  config:
    enable: true
    path: fs.service.business.staffservice
    host: ${server.gateway.ip}:${server.gateway.port}
  api:
    title: 认证授权服务 Api文档
    terms-of-service-url: http://${server.gateway.ip}:${server.gateway.port}/oauth
