spring:
  application:
    name: service-auth
  # redis configuration
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        max-wait: -1ms
        min-idle: 2
      shutdown-timeout: 200
    password: hejian.1
    port: 6379
    timeout: 5000
    database: 0
ibatis:
  typeAliasesPackage: com.learn.*.po
  mapper:
    locations:
      test: classpath:mapper/test/*.xml

datasource:
  name: fsAppByCatering
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jdbc-url: jdbc:sqlserver://47.111.168.225:8899;DatabaseName=fsAppByCatering
  username: fstest
  password: Fsgf@2017

server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    #logging.level.org.springframework.security: DEBUG

